version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - C:\developer\docker\rabbitmq\data:/var/lib/rabbitmq/
        - C:\developer\docker\rabbitmq\log:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  db:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
      command: --default-authentication-plugin=mysql_native_password
    volumes:
      - C:\developer\docker\mysql\data:/var/lib/mysql
      - C:\developer\docker\mysql\conf.d:/etc/mysql/conf.d

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - C:\developer\docker\mongo\data:/data/db

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"
    volumes:
     - C:\developer\docker\redis-data:/var/lib/redis
     - C:\developer\docker\redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4

networks:
  rabbitmq_go_net:
    driver: bridge

  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
